In [6]:
# Q-1-write a pythn program to take a 3X3 matrix as a user input.Convert the matrix in to numpy array. print the matrix,rank,shape of the matrix.
import numpy as np

In [12]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(x.ndim)#range

2


In [9]:
print(x.shape)

(3, 3)


In [15]:
print(x.dtype)

int32


In [8]:
print(x.size)

9


In [11]:
y=np.array(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Q-2-Write a function that generate 10 integers and use it to build an array.

In [17]:
import numpy as np

In [19]:
f=np.arange(1,11)

In [25]:
print("/n (1,11) /n",f)

/n (1,11) /n [ 1  2  3  4  5  6  7  8  9 10]


In [27]:
a=np.array(f)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# Q-3-Create a random vector of size 10 and sort it.

In [41]:
from random import randint

In [47]:
a1=np.random.randint(1,21,10)
a1

array([ 7,  7, 18,  8, 15,  2, 15, 12,  4,  5])

In [49]:
sortedlist=[]

In [50]:
sortedlist=sorted(a1)
print(sortedlist)

[2, 4, 5, 7, 7, 8, 12, 15, 15, 18]


In [ ]:
#Q-4-Write a python program to generate five random numbers from the normal distribution.

In [51]:
a2=np.random.normal(1,12,5)
a2

array([ 5.90474089, -5.80548993, 24.16770813, -4.97718867, 30.22488303])

In [ ]:
#Q-5-Write a numpy program to add and subtract 2 random matrices.The size of the matrix wi be a user input.All the matrix elements should be positive integer value.Suppose 'A'and 'B' are two matrices.All the value of 'A'cannot be greater than 10 and values matrix 'B'cannot be greater  than 20. 

In [53]:
A=np.arange(1,10).reshape(3,3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
B=np.arange(11,20).reshape(3,3)
print(B)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [56]:
np.add(A,B)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [57]:
np.subtract(A,B)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [ ]:
#Q-6-Write a numpy program to multiply two random numbers.The size of the matrix wi be a user input.All the matrix elements should be positive integer value.Suppose 'A'and 'B' are two matrices.All the value of 'A' and 'B' matrices cannot be greater than 10.

In [75]:
A=np.array([[3,2,1]]) 
print (A)

[[3 2 1]]


In [80]:
B=np.array([2,3,5,1,4,3]).reshape(2,3)
print (B)

[[2 3 5]
 [1 4 3]]


In [81]:
m=np.multiply(A,B)
print(m)

[[6 6 5]
 [3 8 3]]


In [ ]:
#Q-7-Write a python program 4.py to take nXm matrix as a user input. 'n' and 'm' are command line
#argument which are separated by a space. Where n >= 3 and 0>=m<=7. If this condition is
#false, ask the user to enter the 'n' and 'm' again. Create a zero matrix with same dimension
#and convert all columns in the matrix into a fibonacci series. For ith column, the first element
#should be the sum of i+(i-1) value. Print this matrix on the terminal.