In [54]:
import numpy as np

In [55]:
#Exercise 1- How to replace items that satisfy a condition with another value in numpy array?

In [56]:
arr_array=np.array([1,2,3,4,5,6,7,8,9])

In [51]:
print(arr_array)

[1 2 3 4 5 6 7 8 9]


In [52]:
for i in arr_array:
    if (i%2!=0):
        print(i,-1)
        

1 -1
3 -1
5 -1
7 -1
9 -1


In [97]:
arr_array1=np.where(arr_array % 2 == 1,-1,arr_array)
arr_array
arr_array1

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [60]:
#Exercise 2: How to reshape an array?

In [61]:
a1=np.array(range(10))
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a2=a1.reshape(1,2,5)
a2

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [101]:
a2=a1.reshape(2,-1)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
#How to generate custom sequences in numpy without hardcoding?

In [70]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [71]:
np.r_[np.repeat(arr,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [78]:
np.r_[np.repeat(1,1),np.repeat(2,2),np.repeat(3,3)]

array([1, 2, 2, 3, 3, 3])

In [79]:
#Exercise 5: How to get the positions where elements of two arrays match?

In [91]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [92]:
b=np.array([7,2,1,2,7,4,9,4,9,8])
b

array([7, 2, 1, 2, 7, 4, 9, 4, 9, 8])

In [94]:
a[np.where(a==b)]

array([2, 2, 4, 4])

In [95]:
b[np.where(a!=b)]

array([7, 1, 7, 9, 9, 8])

In [96]:
#Exercise 6: How to create a 2D array containing random floats between 5 and 10?

In [106]:
rand_arr=np.random.randint(5,10,(5,3)) + np.random.random((5,3))
rand_arr

array([[7.42110151, 8.58639229, 7.96730568],
       [5.83448473, 9.30462018, 8.92632553],
       [8.27742366, 8.465101  , 8.13183587],
       [5.71582872, 5.59974892, 6.03277507],
       [6.64144757, 9.1959697 , 5.16761167]])

In [107]:
#Exercise 7: How to limit the number of items printed in output of numpy array to 6?

In [113]:
arr=np.arange(15)
arr

array([ 0,  1,  2, ..., 12, 13, 14])

In [115]:
arr[np.set_printoptions(threshold=6)]

array([[ 0,  1,  2, ..., 12, 13, 14]])

In [ ]:
#Exercise 8: How to pretty print a numpy array by suppressing the scientific notation (like 1el0)?

In [116]:
np.random.seed(100)

In [118]:
rand_arr=np.random.random([3,3])/1e3

In [121]:
rand_arr[np.set_printoptions(suppress=False)]

array([[[0.000575, 0.000891, 0.000209],
        [0.000185, 0.000108, 0.00022 ],
        [0.000979, 0.000812, 0.000172]]])

In [122]:
rand_arr[np.set_printoptions(suppress=True,precision=6)]

array([[[0.000575, 0.000891, 0.000209],
        [0.000185, 0.000108, 0.00022 ],
        [0.000979, 0.000812, 0.000172]]])

In [ ]:
#Exercise 10: How to swap two rows in a 2d numpy array?

In [130]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
arr[[1,0,2],:]# to swap 1st row and 2nd row in the array,arr 

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [132]:
#Exercise 9: How to swap two columns in a 2d numpy array?

In [133]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])