1. Write a python program to take a 3X3 matrix as a user input. Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix.

In [1]:
import numpy as np
list_1 =list(map(int,input('''Please input your first row:
Enter the entries in a single line (separated by space)
''' ).split()))

list_2 =list(map(int,input('''Please input your second row:
Enter the entries in a single line (separated by space)
''' ).split()))
list_3 =list(map(int,input('''Please input your third row:
Enter the entries in a single line (separated by space)
''' ).split()))
lst=[]
lst.append(list_1)
lst.append(list_2)
lst.append(list_3)
print(f'''

Matrix
{lst}''')

a=np.array(lst)


print(f'''

As array 
{a}
''')

j=a.ndim
h=a.shape
print(f''' 
Rank 
{j}
''')
print(f''' 
shape
{h}
''')

Please input your first row:
Enter the entries in a single line (separated by space)
2 3 4
Please input your second row:
Enter the entries in a single line (separated by space)
5 6 7
Please input your third row:
Enter the entries in a single line (separated by space)
8 9 0


Matrix
[[2, 3, 4], [5, 6, 7], [8, 9, 0]]


As array 
[[2 3 4]
 [5 6 7]
 [8 9 0]]

 
Rank 
2

 
shape
(3, 3)



2. Write a function that generates 10 integers and use it to build an array

In [2]:
r =range(10)
print(r)
a =np.array(r)
print(a)

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]


3. Create a random vector (1D array) of size 10 and sort it

In [3]:
rand =list(np.random.randint(0,100,10))
print(f"Random list of 10 numbers is {rand}")

k = sorted(rand)
print(f"Sorted list of the above is {k}")

Random list of 10 numbers is [36, 40, 6, 11, 48, 22, 17, 69, 0, 84]
Sorted list of the above is [0, 6, 11, 17, 22, 36, 40, 48, 69, 84]


4.Write a Python program to generate five random numbers from the normal distribution.
[Hint: use np.random.normal]

In [4]:
q =np.random.normal(size=5)
print(q)

[-0.50032697 -0.0210828   2.55563058  1.24723016 -0.23859437]


5.Write a numpy program program to add and subtract two random matrices. The size of the
matrix will a user input. All the matrix element should be a positive integer value. Suppose
'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of
'B' matrix cannot be greater than 20.

In [5]:
n= int(input('''Please enter the number of rows:
'''))
m=int(input('''Please enter the number of columns:
'''))
a=np.random.randint(1,10,(n,m))
print(f'''
 A
{a}
''')

b=np.random.randint(1,20,(n,m))
print(f'''
 B
{b}
''')

q=a+b
print(f'''
 Addition
{q}
''')
k=a-b
print(f'''
 Subtraction
{k}
''')

Please enter the number of rows:
3
Please enter the number of columns:
6

 A
[[9 8 9 5 8 1]
 [9 6 8 6 9 2]
 [8 6 8 8 6 7]]


 B
[[ 4  3  9 10 19  5]
 [ 2  8 10 14  5  8]
 [ 9 12  2 15 19 10]]


 Addition
[[13 11 18 15 27  6]
 [11 14 18 20 14 10]
 [17 18 10 23 25 17]]


 Subtraction
[[  5   5   0  -5 -11  -4]
 [  7  -2  -2  -8   4  -6]
 [ -1  -6   6  -7 -13  -3]]



6. Write a numpy program program to multiply two random matrices. The size of the matrices
will a user input. All the matrix element should be a positive integer value. Suppose 'A' and
'B' are two matrix. All the value of 'A', 'B' matrices cannot be greater than 10. Example :

In [6]:
n= int(input('''Please enter the number of rows for matrix 1:
'''))
m=int(input('''Please enter the number of columns for matrix 1:
'''))
p= int(input('''Please enter the number of rows for matrix 2:
'''))
q=int(input('''Please enter the number of columns for matrix 2:
'''))
a=np.random.randint(1,10,(n,m))
print(f'''
 A
{a}
''')

b=np.random.randint(1,10,(p,q))
print(f'''
 B
{b}
''')

t=np.dot(a,b)
print(f'''
 Multiplication
{t}
''')


Please enter the number of rows for matrix 1:
6
Please enter the number of columns for matrix 1:
7
Please enter the number of rows for matrix 2:
7
Please enter the number of columns for matrix 2:
8

 A
[[2 9 2 9 7 7 4]
 [6 6 1 4 4 1 8]
 [8 8 2 6 7 7 3]
 [1 6 2 1 7 7 3]
 [1 7 2 4 8 5 1]
 [1 2 2 5 3 8 4]]


 B
[[1 3 3 5 6 4 6 2]
 [4 4 4 1 2 9 1 2]
 [6 7 4 6 8 7 4 1]
 [4 2 8 2 8 9 6 2]
 [3 2 7 4 3 6 7 4]
 [8 4 4 8 6 1 5 9]
 [2 4 3 6 9 6 5 9]]


 Multiplication
[[171 132 211 157 217 257 187 169]
 [ 88 101 134 122 178 194 143 130]
 [159 136 198 174 218 239 199 164]
 [124  97 129 127 132 148 125 136]
 [123  93 150 110 131 176 131 112]
 [122  89 124 129 159 131 127 138]]



Write a python program 4.py to take nXm matrix as a user input. 'n' and 'm' are command line
argument which are separated by a space. Where n >= 3 and 0>=m<=7. If this condition is
false, ask the user to enter the 'n' and 'm' again. Create a zero matrix with same dimension
and convert all columns in the matrix into a fibonacci series. For i th column, the first element
should be the sum of i+(i-1) value. Print this matrix on the terminal.

In [2]:
#7. Write a python program 4.py to take nXm matrix as a user input. 'n' and 'm' are command line argument which are separated by a space. Where n >= 3 and 0>=m<=7. If this condition is false, ask the user to enter the 'n' and 'm' again. Create a zero matrix with same dimension and convert all columns in the matrix into a fibonacci series. For i th column, the first element should be the sum of i+(i-1) value. Print this matrix on the terminal.
import numpy as np

n = int(input("Enter the number of rows:")) 
m = int(input("Enter the number of columns:")) 

if n>3 and 0<m<=7:
    s=(n,m)
    matrix = np.zeros(s)
    print(f'''
The {n} x {m} zero matrix is:        
{matrix}''')

else:
    print("enter n and m again")

rows = matrix.shape[0]
cols = matrix.shape[1]   
    
    
def Fibonacci(n): 
    if n<0: 
        return 0
    # First Fibonacci number is 0 
    elif n==0: 
        return 0
    # Second Fibonacci number is 1 
    elif n==1: 
        return 1
    else: 
        return Fibonacci(n-1)+Fibonacci(n-2) 
k=0

for i in range(0,rows):
    for j in range(0, cols):
        matrix[i,j] = Fibonacci(i+j)
        

    
print(f''' 
The Fibonacci matrix is:
{matrix}''')


Enter the number of rows:4
Enter the number of columns:6

The 4 x 6 zero matrix is:        
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
 
The Fibonacci matrix is:
[[ 0.  1.  1.  2.  3.  5.]
 [ 1.  1.  2.  3.  5.  8.]
 [ 1.  2.  3.  5.  8. 13.]
 [ 2.  3.  5.  8. 13. 21.]]
