In [45]:
import numpy as np
import sys

#### 1. Replace all odd numbers in arr with -1

In [ ]:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'''
array:
{arr}''')

arr[arr%2 !=0] =-1 

print(f'''
modified array:
{arr}''')

#### Convert a 1D array to a 2D array with 2 rows

In [ ]:
arr = np.arange(10)
print(f'''
array:
{arr}''')
arr =arr.reshape(2,-1)

print(f'''
reshaped array with 2 rows:
{arr}''')

#### 3. Create the following pattern without hardcoding. Use only numpy functions and the below input array arr =np.array([1,2,3]). Desired Output:array ([1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
arr =np.array([1,2,3])
print(f'''
array:
{arr}''')
a= np.repeat(arr[0],2)
b=np.repeat(arr[1],3)
c=np.repeat(arr[2],3)
d=np.tile(arr,3)
k = np.r_[a,b,c,d]
print(f'''
desired output pattern:
{k}''')

#### Get the common items between a and b a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:


a = np.array([1,2,3,2,3,4,3,4,5,6])
print(f'''
array a:
{a}''')
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f'''
array b:
{b}''')
com = np.intersect1d(a,b)

print(f'''
common items:
{com}''')



#### Get the positions where elements of a and b match.a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
print(f'''
array a:
{a}''')
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f'''
array b:
{b}''')
match = np.where(a == b)

print(f'''
a and b match at index locations:
{match}''')



array a:
[1 2 3 2 3 4 3 4 5 6]

array b:
[ 7  2 10  2  7  4  9  4  9  8]

a and b match at index locations:
(array([1, 3, 5, 7]),)


#### Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [ ]:
a= np.random.uniform(5,10,size=15).reshape(5,3)
print(f'''
2D array of shape 5x3 to contain random decimal numbers between 5 and 10:
{a}''')

#### Limit the number of items printed in python numpy array a to a maximum of 6 elements. arr = np.arange(15). Desired Output:array([ 0, 1, 2, ..., 12, 13, 14])

In [49]:
arr = np.arange(15)
print(f'''
array:
{arr}''')

np.set_printoptions(threshold=6)

print(f'''
same array with maximum 6 elements displayed:
{arr}''')
np.set_printoptions(threshold=sys.maxsize)


array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

same array with maximum 6 elements displayed:
[ 0  1  2 ... 12 13 14]


#### How to pretty print a numpy array by suppressing the scientific notation (like 1el0)?

#### np.random.seed(100)
#### rand_arr=np.random.random([3,3])/1e3
#### Desired Output:array([[ 0.000543, 0.000278, 0.000425], [ 0.000845, 0.000005, 0.000122], [ 0.000671 , 0.000826, 0.0001371]])

In [42]:
np.random.seed(100)
rand_arr=np.random.random_sample([3,3])/1e3
print(f'''
array:
{rand_arr}''')
np.set_printoptions(suppress=True, precision=6)
print(f'''
array:
{rand_arr}''')
np.set_printoptions(precision =9, suppress =False)


array:
[[5.434049418e-04 2.783693851e-04 4.245175907e-04]
 [8.447761323e-04 4.718856191e-06 1.215691208e-04]
 [6.707490847e-04 8.258527551e-04 1.367065897e-04]]

array:
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


#### Swap columns 1 and 2 in the array arr.
#### arr = np.arange(9).reshape(3,3)

In [55]:
arr = np.arange(9).reshape(3,3)
print(f'''
array:
{arr}''')
u= arr[:, [1, 0, 2]]
    
print(f'''
array with 1st and 2nd columns swapped:
{u}''')


array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

array with 1st and 2nd columns swapped:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swap rows 1 and 2 in the array arr:
#### arr = np.arange(9).reshape(3,3)

In [56]:
arr = np.arange(9).reshape(3,3)
print(f'''
array:
{arr}''')
u= arr[[1, 0, 2],:]
    
print(f'''
array with 1st and 2nd rows swapped:
{u}''')


array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

array with 1st and 2nd rows swapped:
[[3 4 5]
 [0 1 2]
 [6 7 8]]
