#### Multiply the two matrices.
#### Input : X = [[1, 4, 3],[3, 5, 6],[6, 7, 9]]
#### Y = [[1, 2, 5, 12],[6, 7, 3, 0],[4, 7, 9, 11]]

In [2]:
import numpy as np

X = [[1, 4, 3],[3, 5, 6],[6, 7, 9]]
Y = [[1, 2, 5, 12],[6, 7, 3, 0],[4, 7, 9, 11]]
print(f'''
 X :
{X}''')

print(f'''
 Y :
{Y}''')


a=np.array(X)

b =np.array(Y)
c=(np.dot(a,b))
print(f'''
multiplication of matrices X and Y:
{c}''')


 X :
[[1, 4, 3], [3, 5, 6], [6, 7, 9]]

 Y :
[[1, 2, 5, 12], [6, 7, 3, 0], [4, 7, 9, 11]]

multiplication of matrices X and Y:
[[ 37  51  44  45]
 [ 57  83  84 102]
 [ 84 124 132 171]]


#### Extract all numbers divisible by 3 from the array
#### Input:
#### arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
print(f'''
 array:
{arr}''')
arr[arr%3==0]




 array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


array([ 0,  3,  6,  9, 12])

3. How to get the unique common items between two python numpy arrays?
Q. Get the unique common items between a and b
Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:
array([2, 4])

In [6]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
print(f'''
 array a:
{a}''')

print(f'''
 array b:
{b}''')

com = np.intersect1d(a,b)
print(f'''
 unique common items between a and b :
{com}''')


 array a:
[1 2 3 2 3 4 3 4 5 6]

 array b:
[ 7  2 10  2  7  4  9  4  9  8]

 unique common items between a and b :
[2 4]


4. How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b
Input:
a = np.array([1,2,3,4,5,11,22,33,44,55])
b = np.array([5,6,7,8,9,10,11])
Desired Output:
array([1,2,3,4,22,33,44,55])

In [16]:
a = np.array([1,2,3,4,5,11,22,33,44,55]) 
b = np.array([5,6,7,8,9,10,11]) 
print(f'''
 array a:
{a}''')

print(f'''
 array b:
{b}''')
c =np.setdiff1d(a,b)
print(f'''
 array a,  after removing common items found in b :
{c}''')



 array a:
[ 1  2  3  4  5 11 22 33 44 55]

 array b:
[ 5  6  7  8  9 10 11]

 array a,  after removing common items found in b :
[ 1  2  3  4 22 33 44 55]


5. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match
Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f'''
 array a:
{a}''')

print(f'''
 array b:
{b}''')
k = np.where(a == b)
k
print(f'''
index positions where array a and b match is:
{k}''')


 array a:
[1 2 3 2 3 4 3 4 5 6]

 array b:
[ 7  2 10  2  7  4  9  4  9  8]

index positions where array a and b match is:
(array([1, 3, 5, 7]),)


Create a 2D array of shape 5x3 to contain random decimal numbers between 10 and 25.

In [18]:
arr=np.random.uniform(10,25,size=15).reshape(5,3)
print(f'''
 array :
{arr}''')


 array :
[[22.63685708 13.1530685  21.16397802]
 [11.66277294 18.71042433 11.21491189]
 [21.36270676 21.13811523 20.90967172]
 [20.70012504 14.38011771 24.48559911]
 [19.43858261 20.96278424 18.25716314]]


Take a string as input. Create a new string that is the reverse of the first string.
    A =”Hello”
    Result = “olleH”

In [23]:
A = "Hello"
print(f'''
string:
{A}''')
B =A[::-1]
print(f'''
string reversed:
{B}''')





string:
Hello

string reversed:
olleH


Write a Python program to remove the first occurrence of a specified element  (ex 7 ) from an array.
   Repeat the same for all occurrences of 7

In [29]:

arr = np.array([1,2,3,4,5,6,7,8, 9,7,11,7])


flatten_list = list(arr)

for i in flatten_list:
    if i==7:
        flatten_list.remove(i)
        break


k =np.array(flatten_list)
print(f''' 
array is:
{arr}
''')    
       
print(f''' 
array after removing the first occurrence of a 7 is:
{k}''')    




 
array is:
[ 1  2  3  4  5  6  7  8  9  7 11  7]

 
array after removing the first occurrence of a 7 is:
[ 1  2  3  4  5  6  8  9  7 11  7]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8, 9,7,11,7])


flatten_list = list(arr)

for i in flatten_list:
    if i==7:
        flatten_list.remove(i)

        
k =np.array(flatten_list)
print(f''' 
array is:
{arr}
''')    
       
print(f''' 
array after removing the all occurrences of 7 is:
{k}''') 

 
array is:
[ 1  2  3  4  5  6  7  8  9  7 11  7]

 
array after removing the all occurrences of 7 is:
[ 1  2  3  4  5  6  8  9 11]


Write a Python program that iterate over elements repeating each as many times as its count.

In [1]:
list_1 = [1, 3, 5, 7, 9]
l=[]
for p in list_1:
    for q in range(p):
        l.append(p)
        
print(l)            

[1, 3, 3, 3, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9]


#### Write a Python program to find the occurrences of 10 most common words in a given text.Do the same for words which are at least 4 characters long.

In [4]:
import operator
import itertools  

def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

k = word_count("Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. Machine learning focuses on the development of computer programs that can access data and use it learn for themselves.")
sorted_d = sorted(k.items(), key=operator.itemgetter(1))
sorted_d = dict( sorted(k.items(), key=operator.itemgetter(1),reverse=True))
out = dict(itertools.islice(sorted_d.items(), 10)) 
print(f''' 
10 most common words in a given text along with their count is:
{out}''')

 
10 most common words in a given text along with their count is:
{'Machine': 2, 'learning': 2, 'of': 2, 'that': 2, 'the': 2, 'learn': 2, 'and': 2, 'is': 1, 'an': 1, 'application': 1}


In [3]:
import operator
import itertools  

def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if len(list(word))<= 3:
                continue
        if word in counts:
            
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

k = word_count("Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. Machine learning focuses on the development of computer programs that can access data and use it learn for themselves.")
sorted_d = sorted(k.items(), key=operator.itemgetter(1))
sorted_d = dict( sorted(k.items(), key=operator.itemgetter(1),reverse=True))
out = dict(itertools.islice(sorted_d.items(), 10)) 
print(f''' 
10 most common words in a given text, which are atleast 4 characters long, along with their count is:

{out}''')

 
10 most common words in a given text, which are atleast 4 characters long, along with their count is:

{'Machine': 2, 'learning': 2, 'that': 2, 'learn': 2, 'application': 1, 'artificial': 1, 'intelligence': 1, '(AI)': 1, 'provides': 1, 'systems': 1}


#### 11. Create a python program to generate the Fibonocci series.

In [4]:
def Fibonocci(n):
    lis =[]
    first_num =0
    second_num =1
    if n<=0:
        return print("Not a valid input")
    elif n==1:
        lis.append(n)
        return lis
    else:
        k=1
        for i in range(0,n):
            lis.append(k)
            k = second_num + first_num
            first_num =second_num
            second_num = k
            
        return lis
k =int(input('''Enter the numbers of elements required in your Fibonacci series
'''))    
Fibonocci(k)

Enter the numbers of elements required in your Fibonacci series
18


[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584]