# 1. Write a python program to take a 3X3 matrix as a user input. Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix. 

In [3]:
import numpy as np
from numpy import matrix, rank

In [4]:
mat = [[int(input()) for x in range (3)]for y in range(3)]  #take row wise input from user

1
2
3
4
5
6
7
8
9


In [6]:
mat1=np.matrix(mat)                     ##convert a list to matrix

In [7]:
print(mat1)                             ##print a matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
mat1.shape                              ##shape of matrix

(3, 3)

In [9]:
rank(mat1)                              ##rank of matrix

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  """Entry point for launching an IPython kernel.


2

In [12]:
arr=np.array(mat1).flatten()##convert matrix to array
print(arr)

[1 2 3 4 5 6 7 8 9]


# 2. Write a function that generates 10 integers and use it to build an array 

In [13]:
import numpy as np
import random

In [16]:
randomlist = random.sample(range(0, 30), 10)
print(randomlist)                                               ##created a random list
arr1=np.array(randomlist)                                       ##converted list to array
arr1

[28, 8, 21, 11, 13, 23, 3, 14, 1, 27]


array([28,  8, 21, 11, 13, 23,  3, 14,  1, 27])

# 3. Create a random vector (1D array) of size 10 and sort it  

In [17]:
import numpy as np
import random

In [18]:
rand=random.sample(range(1,40), 10)
arr2=np.array(rand)
arr2

array([16, 25, 39, 37, 29, 12,  5,  2,  9,  6])

In [20]:
arr2.sort()
arr2

array([ 2,  5,  6,  9, 12, 16, 25, 29, 37, 39])

# 4. Write a Python program to generate five random numbers from the normal distribution. 

In [29]:
import numpy as np
rand_nor= np.random.normal(size=5)
rand_nor

array([ 0.33909074, -0.40591885,  1.20215178, -1.67779588, -0.69345459])

# 5. Write a numpy program program to add and subtract two random matrices. The size of the matrix will a user input. All the matrix element should be a positive integer value. Suppose  'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of 'B' matrix cannot be greater than 20.  